import type { ThemeTokens } from '../types';

export const lightTokens: ThemeTokens = {
  colorBackground: '#f5f5f5',
  colorSurface: '#ffffff',
  colorSurfaceHover: '#ebebeb',
  colorBorder: '#d0d0d0',
  colorText: '#1a1a1a',
  colorTextMuted: '#6b6b6b',
  colorPrimary: '#4a6cf7',
  colorPrimaryHover: '#3a5ce6',
  colorDanger: '#e53e3e',
  colorSuccess: '#38a169',
  colorWarning: '#d69e2e',
  fontFamily: "'Inter', system-ui, sans-serif",
  fontSizeBase: '14px',
  fontSizeSm: '12px',
  fontSizeLg: '16px',
  spacingXs: '4px',
  spacingSm: '8px',
  spacingMd: '16px',
  spacingLg: '24px',
  spacingXl: '32px',
  borderRadius: '6px',
  borderRadiusLg: '12px',
  shadowSm: '0 1px 3px rgba(0,0,0,0.1)',
  shadowMd: '0 4px 12px rgba(0,0,0,0.12)',
  shadowLg: '0 8px 24px rgba(0,0,0,0.15)',
  transitionFast: '100ms ease',
  transitionBase: '200ms ease',
  zIndexWindow: 100,
  zIndexModal: 300,
  zIndexNotification: 400,
  zIndexContextMenu: 500,
};
